# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]

months.each do |month|
  Month.create(name: month)
end


vegetables = [
  {name: "Artichokes", months: ["August", "September", "October"], :measure=>"1 medium", :weight=>120, :calories=>60, :protein=>4, :carbohydrate=>13, :total_sugar=>1, :total_dietary_fibre=>4.7, :calcium=>54, :iron=>1.5, :sodium=>114, :potassium=>425, :vitamin_a=>11, :vitamin_c=>12, :vitamin_b12=>0},
  {name: "Asparagus", months: ["May", "June"], :measure=>"6 spears", :weight=>90, :calories=>18, :protein=>2, :carbohydrate=>3, :total_sugar=>1, :total_dietary_fibre=>1.6, :calcium=>18, :iron=>0.7, :sodium=>8, :potassium=>178, :vitamin_a=>41, :vitamin_c=>14, :vitamin_b12=>0},
  {name: "Beets", months: ["January", "February", "March", "April", "July", "August", "September", "October", "November", "December"], :measure=>"125mL", :weight=>90, :calories=>40, :protein=>2, :carbohydrate=>9, :total_sugar=>7, :total_dietary_fibre=>1.8, :calcium=>14, :iron=>0.7, :sodium=>69, :potassium=>274, :vitamin_a=>2, :vitamin_c=>3, :vitamin_b12=>0},
  {name: "Brocolli", months: ["June", "July", "August", "September", "October"], :measure=>"125mL", :weight=>46, :calories=>16, :protein=>1, :carbohydrate=>3, :total_sugar=>1, :total_dietary_fibre=>1.1, :calcium=>22, :iron=>0.3, :sodium=>15, :potassium=>147, :vitamin_a=>15, :vitamin_c=>41, :vitamin_b12=>0},
  {name: "Brussels Sprouts", months: ["September", "October", "November"], :measure=>"4 sprouts", :weight=>84, :calories=>33, :protein=>3, :carbohydrate=>6, :total_sugar=>2, :total_dietary_fibre=>3.2, :calcium=>26, :iron=>0.7, :sodium=>15, :potassium=>255, :vitamin_a=>36, :vitamin_c=>45, :vitamin_b12=>0},
  {name: "Cabbage", months: ["January", "February", "March", "April", "June", "July", "August", "September", "October", "November", "December"], :measure=>"125mL", :weight=>37, :calories=>9, :protein=>1, :carbohydrate=>2, :total_sugar=>1, :total_dietary_fibre=>0.7, :calcium=>17, :iron=>0.2, :sodium=>7, :potassium=>91, :vitamin_a=>3, :vitamin_c=>12, :vitamin_b12=>0},
  {name: "Cauliflower", months: ["June", "July", "August", "September", "October", "November"], :measure=>"125mL", :weight=>53, :calories=>13, :protein=>1, :carbohydrate=>3, :total_sugar=>1, :total_dietary_fibre=>0.9, :calcium=>12, :iron=>0.2, :sodium=>16, :potassium=>160, :vitamin_a=>1, :vitamin_c=>25, :vitamin_b12=>0},
  {name: "Celery", months: ["July", "August", "September", "October"], :measure=>1, :weight=>40, :calories=>6, :protein=>"tr", :carbohydrate=>1, :total_sugar=>1, :total_dietary_fibre=>0.6, :calcium=>16, :iron=>0.1, :sodium=>32, :potassium=>104, :vitamin_a=>9, :vitamin_c=>1, :vitamin_b12=>0},
  {name: "Cucumbers", months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], :measure=>"4 slices", :weight=>28, :calories=>3, :protein=>"tr", :carbohydrate=>1, :total_sugar=>"tr", :total_dietary_fibre=>0.2, :calcium=>4, :iron=>0.1, :sodium=>1, :potassium=>38, :vitamin_a=>1, :vitamin_c=>1, :vitamin_b12=>0},
  {name: "Eggplant", months: ["August", "September", "October"], :measure=>"125mL", :weight=>52, :calories=>18, :protein=>"tr", :carbohydrate=>5, :total_sugar=>2, :total_dietary_fibre=>1.3, :calcium=>3, :iron=>0.1, :sodium=>1, :potassium=>64, :vitamin_a=>1, :vitamin_c=>1, :vitamin_b12=>0},
  {name: "Lettuce", months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], :measure=>"250mL", :weight=>58, :calories=>8, :protein=>1, :carbohydrate=>2, :total_sugar=>1, :total_dietary_fibre=>0.7, :calcium=>10, :iron=>0.2, :sodium=>6, :potassium=>82, :vitamin_a=>15, :vitamin_c=>2, :vitamin_b12=>0},
  {name: "Mushrooms", months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], :measure=>"3 medium", :weight=>54, :calories=>12, :protein=>2, :carbohydrate=>2, :total_sugar=>1, :total_dietary_fibre=>0.6, :calcium=>2, :iron=>0.3, :sodium=>2, :potassium=>170, :vitamin_a=>0, :vitamin_c=>1, :vitamin_b12=>0.02},
  {name: "Okra", months: ["January", "February", "March", "December"], :measure=>"100mL", :weight=>100, :calories=>33, :protein=>1.9, :carbohydrate=>7, :total_sugar=>1.5, :total_dietary_fibre=>3.2, :calcium=>8, :iron=>3, :sodium=>7, :potassium=>299, :vitamin_a=>14, :vitamin_c=>38, :vitamin_b12=>0},
  {name: "Onions", months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], :measure=>"60mL", :weight=>41, :calories=>17, :protein=>"tr", :carbohydrate=>4, :total_sugar=>2, :total_dietary_fibre=>0.6, :calcium=>9, :iron=>0.1, :sodium=>1, :potassium=>58, :vitamin_a=>0, :vitamin_c=>3, :vitamin_b12=>0},
  {name: "Peppers", months: ["March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], :measure=>"  1/2 ", :weight=>60, :calories=>15, :protein=>1, :carbohydrate=>4, :total_sugar=>2, :total_dietary_fibre=>0.8, :calcium=>4, :iron=>0.3, :sodium=>1, :potassium=>126, :vitamin_a=>93, :vitamin_c=>113, :vitamin_b12=>0},
  {name: "Potatoes", months: ["January", "February", "March", "July", "August", "September", "October", "November", "December"], :measure=>1, :weight=>173, :calories=>161, :protein=>4, :carbohydrate=>37, :total_sugar=>2, :total_dietary_fibre=>3.8, :calcium=>26, :iron=>1.9, :sodium=>17, :potassium=>926, :vitamin_a=>2, :vitamin_c=>17, :vitamin_b12=>0},
  {name: "Pumpkins", months: ["September", "October", "November"], :measure=>"125mL", :weight=>129, :calories=>44, :protein=>1, :carbohydrate=>10, :total_sugar=>4, :total_dietary_fibre=>3.8, :calcium=>34, :iron=>1.8, :sodium=>6, :potassium=>267, :vitamin_a=>1007, :vitamin_c=>5, :vitamin_b12=>0},
  {name: "Radishes", months: ["May", "June", "July", "August", "September", "October", "November"], :measure=>"3 medium", :weight=>14, :calories=>2, :protein=>"tr", :carbohydrate=>"tr", :total_sugar=>"tr", :total_dietary_fibre=>0.2, :calcium=>3, :iron=>"tr", :sodium=>5, :potassium=>31, :vitamin_a=>0, :vitamin_c=>2, :vitamin_b12=>0 },
  {name: "Spinach", months: ["May", "June", "July", "August", "September", "October"], :measure=>"250mL", :weight=>32, :calories=>7, :protein=>1, :carbohydrate=>1, :total_sugar=>"tr", :total_dietary_fibre=>0.7, :calcium=>31, :iron=>0.9, :sodium=>25, :potassium=>177, :vitamin_a=>149, :vitamin_c=>9, :vitamin_b12=>0},
  {name: "Squash", months: ["January", "February", "March", "August", "September", "October", "November", "December"], :measure=>"125mL", :weight=>108, :calories=>43, :protein=>1, :carbohydrate=>11, :total_sugar=>2, :total_dietary_fibre=>1.8, :calcium=>44, :iron=>0.6, :sodium=>4, :potassium=>308, :vitamin_a=>413, :vitamin_c=>16, :vitamin_b12=>0},
  {name: "Sweet Potatoes", months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], measure: 1, weight: 133, calories: 114, protein: , carbohydrate: , total_suger: ,total_dietary_fibre: , calcium: , sodium: , potassium: },
  {name: "Zucchini", months: ["July", "August", "September", "October"], :measure=>4, :weight=>40, :calories=>6, :protein=>"tr", :carbohydrate=>1, :total_sugar=>1, :total_dietary_fibre=>0.4, :calcium=>6, :iron=>0.1, :sodium=>4, :potassium=>104, :vitamin_a=>4, :vitamin_c=>7, :vitamin_b12=>0},
  {name: "Carrots", months: ["January", "February", "March", "April", "May", "July", "August", "September", "October", "November", "December"], :measure=>"1 medium", :weight=>61, :calories=>25, :protein=>1, :carbohydrate=>6, :total_sugar=>3, :total_dietary_fibre=>1.5, :calcium=>20, :iron=>0.2, :sodium=>42, :potassium=>195, :vitamin_a=>367, :vitamin_c=>4, :vitamin_b12=>0},
  {name: "Beans", months: ["June", "July", "August", "September", "October"], measure: 12.1, weight: 100, calories: 41, protein: 2.6, carbohydrate: 8, total_suger: 0.3, total_dietary_fibre: 1.9, calcium: 1, sodium: 1, potassium: 179, :vitamin_a=>0, :vitamin_c=>0, :vitamin_b12=>0},
  {name: "Corn", months: ["July", "August", "September", "October"], :measure=>"125mL", :weight=>87, :calories=>82, :protein=>3, :carbohydrate=>19, :total_sugar=>3, :total_dietary_fibre=>2, :calcium=>2, :iron=>0.5, :sodium=>8, :potassium=>209, :vitamin_a=>7, :vitamin_c=>4, :vitamin_b12=>0},
  {name: "Tomatoes", months: ["March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], :measure=>1, :weight=>123, :calories=>22, :protein=>1, :carbohydrate=>5, :total_sugar=>3, :total_dietary_fibre=>1.5, :calcium=>12, :iron=>0.3, :sodium=>6, :potassium=>292, :vitamin_a=>52, :vitamin_c=>16, :vitamin_b12=>0}
]

fruits = [
  {name: "Apples", months: ["August", "September", "October", "November"], measure: 1, weight: 138, calories: 72, protein: "tr", carbohydrate: 19, total_suger: 14,total_dietary_fibre: 2.6, calcium: 8, sodium: 1, potassium: 148:measure=>1, :weight=>138, :calories=>72, :protein=>"tr", :carbohydrate=>19, :total_sugar=>14, :total_dietary_fibre=>2.6, :calcium=>8, :iron=>0.2, :sodium=>1, :potassium=>148, :vitamin_a=>4, :vitamin_c=>6, :vitamin_b12=>0},
  {name: "Apricots", months: ["July", "August"], :measure=>3, :weight=>105, :calories=>50, :protein=>1, :carbohydrate=>12, :total_sugar=>10, :total_dietary_fibre=>2.1, :calcium=>14, :iron=>0.4, :sodium=>1, :potassium=>272, :vitamin_a=>101, :vitamin_c=>11, :vitamin_b12=>0 },
  {name: "Bananas", months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], :measure=>1, :weight=>118, :calories=>105, :protein=>1, :carbohydrate=>27, :total_sugar=>14, :total_dietary_fibre=>2.1, :calcium=>6, :iron=>0.3, :sodium=>1, :potassium=>422, :vitamin_a=>4, :vitamin_c=>10, :vitamin_b12=>0 },
  {name: "Blueberries", months: ["July", "August", "September"], :measure=>"125mL", :weight=>77, :calories=>44, :protein=>1, :carbohydrate=>11, :total_sugar=>8, :total_dietary_fibre=>2, :calcium=>5, :iron=>0.2, :sodium=>1, :potassium=>59, :vitamin_a=>2, :vitamin_c=>7, :vitamin_b12=>0 },
  {name: "Cantaloupe", months: ["June", "July", "August", "September"], :measure=>"125mL", :weight=>85, :calories=>29, :protein=>1, :carbohydrate=>7, :total_sugar=>7, :total_dietary_fibre=>0.6, :calcium=>8, :iron=>0.2, :sodium=>14, :potassium=>226, :vitamin_a=>143, :vitamin_c=>31, :vitamin_b12=>0},
  {name: "Cherries", months: ["June", "July"], :measure=>"60mL", :weight=>31, :calories=>95, :protein=>"tr", :carbohydrate=>25, :total_sugar=>20, :total_dietary_fibre=>1.8, :calcium=>3, :iron=>0.2, :sodium=>1, :potassium=>12, :vitamin_a=>0, :vitamin_c=>"tr", :vitamin_b12=>0 },
  {name: "Cranberries", months: ["October"], :measure=>"60mL", :weight=>31, :calories=>95, :protein=>"tr", :carbohydrate=>25, :total_sugar=>20, :total_dietary_fibre=>1.8, :calcium=>3, :iron=>0.2, :sodium=>1, :potassium=>12, :vitamin_a=>0, :vitamin_c=>"tr", :vitamin_b12=>0},
  {name: "Grapefruit", :measure=>"  1/2 ", :weight=>123, :calories=>52, :protein=>1, :carbohydrate=>13, :total_sugar=>8, :total_dietary_fibre=>2, :calcium=>27, :iron=>0.1, :sodium=>0, :potassium=>166, :vitamin_a=>71, :vitamin_c=>38, :vitamin_b12=>0 },
  {name: "Grapes", months: ["August", "September"], :measure=>20, :weight=>100, :calories=>69, :protein=>1, :carbohydrate=>18, :total_sugar=>15, :total_dietary_fibre=>1.2, :calcium=>10, :iron=>0.4, :sodium=>2, :potassium=>191, :vitamin_a=>3, :vitamin_c=>11, :vitamin_b12=>0 },
  {name: "Kiwi", months: ["January", "February", "March", "April", "May", "October", "November", "December"], :measure=>1, :weight=>76, :calories=>46, :protein=>1, :carbohydrate=>11, :total_sugar=>7, :total_dietary_fibre=>2.3, :calcium=>26, :iron=>0.2, :sodium=>2, :potassium=>237, :vitamin_a=>3, :vitamin_c=>69, :vitamin_b12=>0 },
  {name: "Lemons", months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], measure: , weight: , calories: , protein: , carbohydrate: , total_suger: ,total_dietary_fibre: , calcium: , sodium: , potassium: },
  {name: "Mangoes", months: ["May", "June", "July", "August", "September"], measure: 0.5, weight: 104, calories: 67, protein: 1, carbohydrate: 18, total_sugar: 15, total_dietary_fibre: 1.9, calcium: 10, sodium: 2, potassium: 161},
  {name: "Nectarines", months: ["August", "September"], :measure=>1, :weight=>136, :calories=>60, :protein=>1, :carbohydrate=>14, :total_sugar=>11, :total_dietary_fibre=>2.3, :calcium=>8, :iron=>0.4, :sodium=>0, :potassium=>273, :vitamin_a=>18, :vitamin_c=>7, :vitamin_b12=>0},
  {name: "Oranges", months: ["January", "February", "March", "April", "May", "June", "November", "December"], :measure=>1, :weight=>131, :calories=>62, :protein=>1, :carbohydrate=>15, :total_sugar=>12, :total_dietary_fibre=>2.3, :calcium=>52, :iron=>0.1, :sodium=>0, :potassium=>237, :vitamin_a=>8, :vitamin_c=>70, :vitamin_b12=>0},
  {name: "Papayas", months: ["June", "July", "August", "September"], :measure=>"125mL", :weight=>74, :calories=>29, :protein=>"tr", :carbohydrate=>7, :total_sugar=>4, :total_dietary_fibre=>1.3, :calcium=>18, :iron=>0.1, :sodium=>2, :potassium=>190, :vitamin_a=>17, :vitamin_c=>46, :vitamin_b12=>0},
  {name: "Peaches", months: ["July", "August", "September"], :measure=>1, :weight=>98, :calories=>38, :protein=>1, :carbohydrate=>9, :total_sugar=>8, :total_dietary_fibre=>1.9, :calcium=>6, :iron=>0.2, :sodium=>0, :potassium=>186, :vitamin_a=>16, :vitamin_c=>6, :vitamin_b12=>0},
  {name: "Pears", months: ["August", "September", "October", "November", "December"], :measure=>1, :weight=>166, :calories=>96, :protein=>1, :carbohydrate=>26, :total_sugar=>16, :total_dietary_fibre=>5, :calcium=>15, :iron=>0.3, :sodium=>2, :potassium=>198, :vitamin_a=>2, :vitamin_c=>7, :vitamin_b12=>0},
  {name: "Pineapple", months: ["March", "April", "May", "June", "July"], :measure=>" 125mL", :weight=>82, :calories=>42, :protein=>"tr", :carbohydrate=>11, :total_sugar=>8, :total_dietary_fibre=>1.1, :calcium=>11, :iron=>0.2, :sodium=>1, :potassium=>88, :vitamin_a=>2, :vitamin_c=>46, :vitamin_b12=>0},
  {name: "Plums", months: ["July", "August", "September", "October"], :measure=>1, :weight=>66, :calories=>30, :protein=>"tr", :carbohydrate=>8, :total_sugar=>7, :total_dietary_fibre=>1.1, :calcium=>4, :iron=>0.1, :sodium=>0, :potassium=>104, :vitamin_a=>11, :vitamin_c=>6, :vitamin_b12=>0},
  {name: "Pomegranates", months: ["January", "October", "November", "December"], :measure=>"  1/2 ", :weight=>77, :calories=>53, :protein=>1, :carbohydrate=>13, :total_sugar=>13, :total_dietary_fibre=>0.5, :calcium=>2, :iron=>0.2, :sodium=>2, :potassium=>200, :vitamin_a=>2, :vitamin_c=>5, :vitamin_b12=>0},
  {name: "Raspberries", months: ["July", "August", "September"], :measure=>"125mL", :weight=>65, :calories=>34, :protein=>1, :carbohydrate=>8, :total_sugar=>3, :total_dietary_fibre=>4.2, :calcium=>16, :iron=>0.4, :sodium=>1, :potassium=>98, :vitamin_a=>1, :vitamin_c=>17, :vitamin_b12=>0},
  {name: "Rhubard", months: ["January", "February", "March", "April", "May", "June"], :measure=>"125mL", :weight=>127, :calories=>147, :protein=>"tr", :carbohydrate=>40, :total_sugar=>36, :total_dietary_fibre=>2.5, :calcium=>184, :iron=>0.3, :sodium=>1, :potassium=>122, :vitamin_a=>5, :vitamin_c=>4, :vitamin_b12=>0},
  {name: "Strawberries", months: ["June", "July"], :measure=>7, :weight=>84, :calories=>27, :protein=>1, :carbohydrate=>6, :total_sugar=>4, :total_dietary_fibre=>1.9, :calcium=>13, :iron=>0.4, :sodium=>1, :potassium=>129, :vitamin_a=>1, :vitamin_c=>49, :vitamin_b12=>0},
  {name: "Tangerines", months: ["January", "February", "March", "April", "May"], :measure=>1, :weight=>84, :calories=>45, :protein=>1, :carbohydrate=>11, :total_sugar=>9, :total_dietary_fibre=>1.5, :calcium=>31, :iron=>0.1, :sodium=>2, :potassium=>139, :vitamin_a=>11, :vitamin_c=>22, :vitamin_b12=>0},
  {name: "Watermelon", months: ["July", "August", "September"], :measure=>"125mL", :weight=>80, :calories=>24, :protein=>"tr", :carbohydrate=>6, :total_sugar=>5, :total_dietary_fibre=>0.3, :calcium=>6, :iron=>0.2, :sodium=>1, :potassium=>90, :vitamin_a=>22, :vitamin_c=>7, :vitamin_b12=>0 }
]

vegetables.each do |veg|
  Product.create(name: veg["name"], context: "vegetable")
end

fruits.each do |fruit|
  Product.create(name: fruit["name"], context: "fruit")
end

provinces = [ "Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan"]

provinces.each do |province|
  Province.create(name: province)
end
